import 'package:projeto_de_sistemas/domain/models/products/product.dart';

List<Product> mockProducts = [
    Product(
      id: 1,
      name: 'Smartphone X',
      description: 'Smartphone de última geração',
      category: 'Eletrônicos',
      brand: 'TechBrand',
      market: 'TechStore',
      unityPrice: 599.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000001,
    ),
    Product(
      id: 2,
      name: 'Wireless Headphones',
      description: 'Fones de ouvido sem fio com alta qualidade',
      category: 'Eletrônicos',
      brand: 'AudioBrand',
      market: 'AudioShop',
      unityPrice: 129.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000002,
    ),
    Product(
      id: 3,
      name: 'Smart Watch',
      description: 'Relógio inteligente com monitoramento de saúde',
      category: 'Eletrônicos',
      brand: 'GadgetBrand',
      market: 'GadgetZone',
      unityPrice: 199.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000003,
    ),
    Product(
      id: 4,
      name: 'Smartphone X',
      description: 'Smartphone de última geração',
      category: 'Eletrônicos',
      brand: 'TechBrand',
      market: 'TechStore',
      unityPrice: 599.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000004,
    ),
    Product(
      id: 5,
      name: 'Wireless Headphones',
      description: 'Fones de ouvido sem fio com alta qualidade',
      category: 'Eletrônicos',
      brand: 'AudioBrand',
      market: 'AudioShop',
      unityPrice: 129.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000005,
    ),
    Product(
      id: 6,
      name: 'Smart Watch',
      description: 'Relógio inteligente com monitoramento de saúde',
      category: 'Eletrônicos',
      brand: 'GadgetBrand',
      market: 'GadgetZone',
      unityPrice: 199.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000006,
    ),
    Product(
      id: 7,
      name: 'Cartierm Santos Dumont',
      description: 'Smartphone de última geração',
      category: 'Eletrônicos',
      brand: 'TechBrand',
      market: 'TechStore',
      unityPrice: 599.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000007,
    ),
    Product(
      id: 8,
      name: 'Ozempic',
      description: 'Fones de ouvido sem fio com alta qualidade',
      category: 'Eletrônicos',
      brand: 'AudioBrand',
      market: 'AudioShop',
      unityPrice: 129.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000008,
    ),
    Product(
      id: 9,
      name: 'Penicilina',
      description: 'Relógio inteligente com monitoramento de saúde',
      category: 'Eletrônicos',
      brand: 'GadgetBrand',
      market: 'GadgetZone',
      unityPrice: 199.99,
      quantity: 1,
      expirationDate: DateTime(2026, 12, 31),
      image: '',
      barCode: 1000009,
    ),
  ];